sudo: false
language: python
os:
  - linux
node_js:
  - "stable"
  - "4.1"
cache:
  directories:
    - node_modules
before_install:
  - npm install gitbook-cli -g
  - phantomjs --version

install:
  - gitbook install

before_script:
  - gitbook build
  - cd _book
  - python -m SimpleHTTPServer 8000 &> /dev/null &
  - cd ..

script:
  - phantomjs verify.js localhost:8080/v1
  - phantomjs verify.js localhost:8080/v2
  - phantomjs verify.js localhost:8080/v3
